variables:
  PROJECT_PATH: /go/src/gitlab.com/kentanggoreng
  PROJECT_NAME: quip-server
  FUNCTION_NAME: quip-server

stages:
  - build
  - deploy

build:
  stage: build
  image: golang:latest
  before_script:
    - mkdir -p $PROJECT_PATH
    - ln -s $CI_PROJECT_DIR $PROJECT_PATH
    - go get -v -d $PROJECT_PATH/$PROJECT_NAME
  script:
    - go build -v $PROJECT_PATH/$PROJECT_NAME/main.go
  artifacts:
    paths:
      - main
      
deploy-lambda:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  before_script:
    - apt-get install zip
  script:
    - zip main.zip main
    - aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb://main.zip --region ap-southeast-1 --output json
